#!/bin/zsh

mkdir -p O
rm -f O/bootloader.bin O/ExtendedProgram.o O/Kernel.o kernel.bin bootloader.flp 2>/dev/null

nasm -f bin Sector1/bootloader.asm -o O/bootloader.bin
nasm -f elf64 Sector2+/ExtendedProgram.asm -o O/ExtendedProgram.o

x86_64-elf-g++ -ffreestanding -mno-red-zone -m64 -fno-exceptions -fno-rtti -c "Kernel.cpp" -o "O/Kernel.o"

x86_64-elf-ld -T link.ld

dd if=O/bootloader.bin of=bootloader.flp bs=512 count=1 conv=notrunc status=none
dd if=kernel.bin of=bootloader.flp bs=512 seek=1 conv=notrunc status=none
truncate -s 1440k bootloader.flp