#pragma once

#define FOREGROUND_BLACK 0x00
#define FOREGROUND_BLUE 0x01
#define FOREGROUND_GREEN 0x02
#define FOREGROUND_CYAN 0x03
#define FOREGROUND_RED 0x04
#define FOREGROUND_MAGENTA 0x05
#define FOREGROUND_BROWN 0x06
#define FOREGROUND_LIGHT_GREY 0x07
#define FOREGROUND_DARK_GREY 0x08
#define FOREGROUND_LIGHT_BLUE 0x09
#define FOREGROUND_LIGHT_GREEN 0x0A
#define FOREGROUND_LIGHT_CYAN 0x0B
#define FOREGROUND_LIGHT_RED 0x0C
#define FOREGROUND_LIGHT_MAGENTA 0x0D
#define FOREGROUND_LIGHT_BROWN 0x0E
#define FOREGROUND_WHITE 0x0F

#define BACKGROUND_BLACK 0x00
#define BACKGROUND_BLUE 0x10
#define BACKGROUND_GREEN 0x20
#define BACKGROUND_CYAN 0x30
#define BACKGROUND_RED 0x40
#define BACKGROUND_MAGENTA 0x50
#define BACKGROUND_BROWN 0x60
#define BACKGROUND_LIGHT_GREY 0x70
#define BACKGROUND_BLINKING_BLACK 0x80
#define BACKGROUND_BLINKING_BLUE 0x90
#define BACKGROUND_BLINKING_GREEN 0xA0
#define BACKGROUND_BLINKING_CYAN 0xB0
#define BACKGROUND_BLINKING_RED 0xC0
#define BACKGROUND_BLINKING_MAGENTA 0xD0
#define BACKGROUND_BLINKING_BROWN 0xE0
#define BACKGROUND_BLINKING_LIGHT_GREY 0xF0
