#!/bin/zsh
./scripts/compile

if [ "$1" = "nographics" ]; then
    qemu-system-x86_64 -nographic -drive file=bootloader.flp,format=raw,index=0,media=disk
else
    qemu-system-x86_64 -drive file=bootloader.flp,format=raw,index=0,media=disk
fi

rm kernel.bin bootloader.flp 2>/dev/null

exit 0