#!/bin/zsh
./scripts/compile

if [ "$1" = "nographics" ]; then
    qemu-system-x86_64 -nographic -drive file=bootable/bootloader.flp,format=raw,index=0,if=floppy
else
    qemu-system-x86_64 -drive file=bootable/bootloader.flp,format=raw,index=0,if=floppy
fi

rm bin/kernel.bin bootable/bootloader.flp 2>/dev/null

exit 0